/** @type {import('xo').FlatXoConfig} */
export default [
  {
    ignores: [".next/**", ".open-next/**", ".wrangler/**", "next-env.d.ts", "xo.config.js"],
  },
  {
    prettier: "compat",
    rules: {
      "react/react-in-jsx-scope": "off",
      "@typescript-eslint/naming-convention": "off",
      "import-x/no-unassigned-import": "off",
      "import-x/extensions": "off",
      "import-x/order": "off",
      "import-x/no-duplicates": "off",
      "import-x/newline-after-import": "off",
      "n/no-process-env": "off",
      "unicorn/prevent-abbreviations": "off",
      "unicorn/prefer-ternary": "off",
      "unicorn/no-negated-condition": "off",
      "unicorn/no-array-callback-reference": "off",
      "unicorn/prefer-code-point": "off",
      "unicorn/no-null": "off",
      "unicorn/prefer-module": "off",
      "unicorn/no-array-sort": "off",
      "unicorn/prefer-spread": "off",
      "unicorn/prefer-logical-operator-over-ternary": "off",
      "unicorn/no-await-expression-member": "off",
      "unicorn/prefer-add-event-listener": "off",
      "unicorn/prefer-global-this": "off",
      "unicorn/switch-case-braces": "off",
      "unicorn/prefer-string-raw": "off",
      "unicorn/prefer-export-from": "off",
      "unicorn/prefer-string-replace-all": "off",
      "unicorn/better-regex": "off",
      "unicorn/no-useless-fallback-in-spread": "off",
      "@typescript-eslint/no-restricted-types": "off",
      "@typescript-eslint/no-confusing-void-expression": "off",
      "@typescript-eslint/consistent-type-imports": "off",
      "@typescript-eslint/no-deprecated": "off",
      "@typescript-eslint/no-unsafe-type-assertion": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/prefer-nullish-coalescing": "off",
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/triple-slash-reference": "off",
      "@typescript-eslint/strict-void-return": "off",
      "@typescript-eslint/consistent-type-definitions": "off",
      "@typescript-eslint/consistent-type-assertions": "off",
      "@typescript-eslint/switch-exhaustiveness-check": "off",
      "@typescript-eslint/no-unnecessary-type-assertion": "off",
      "@typescript-eslint/promise-function-async": "off",
      "@typescript-eslint/prefer-regexp-exec": "off",
      "@typescript-eslint/prefer-optional-chain": "off",
      "@typescript-eslint/array-type": "off",
      "@stylistic/padding-line-between-statements": "off",
      "@stylistic/indent": "off",
      "@stylistic/curly-newline": "off",
      "capitalized-comments": "off",
      "prefer-destructuring": "off",
      "no-negated-condition": "off",
      "require-unicode-regexp": "off",
      "max-params": "off",
      "no-alert": "off",
      "no-bitwise": "off",
      "no-void": "off",
      "array-callback-return": "off",
      "object-shorthand": "off",
      "prefer-exponentiation-operator": "off",
      "logical-assignment-operators": "off",
      "arrow-body-style": "off",
    },
  },
];
