export { BookmarkGroupSlot } from "./bookmark-group-slot";
export { Canvas } from "./canvas";
export { CommandBarSlot } from "./command-bar-slot";
export { CommandCenterSlot } from "./command-center-slot";
export { MusicSlot } from "./music-slot";
export { TasksSlot } from "./tasks-slot";
export { TimerSlot } from "./timer-slot";
export { WorkspaceEdges } from "./workspace-edges";
export { YoutubePlayer } from "./youtube-player";
